# Generated by Django 5.1.7 on 2025-04-14 04:00

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_exam_faculty_rename_id_person_id_person_fname_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('email', models.EmailField(max_length=254, primary_key=True, serialize=False)),
                ('nshe', models.CharField(max_length=20)),
                ('role', models.CharField(choices=[('student', 'Student'), ('faculty', 'Faculty')], max_length=10)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.RenameField(
            model_name='exam',
            old_name='ID',
            new_name='id',
        ),
        migrations.RemoveField(
            model_name='exam',
            name='ClassNum',
        ),
        migrations.RemoveField(
            model_name='exam',
            name='Date',
        ),
        migrations.RemoveField(
            model_name='exam',
            name='Procter',
        ),
        migrations.AddField(
            model_name='exam',
            name='booked',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='exam',
            name='capacity',
            field=models.PositiveIntegerField(default=20),
        ),
        migrations.AddField(
            model_name='exam',
            name='location',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='exam',
            name='subject',
            field=models.CharField(default='math', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='exam',
            name='time',
            field=models.TimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.exam')),
                ('email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.user')),
            ],
            options={
                'unique_together': {('email', 'exam')},
            },
        ),
        migrations.DeleteModel(
            name='ExamRegistration',
        ),
        migrations.AddField(
            model_name='exam',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
